//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpentryShop.CarpentryShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentReceipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComponentReceipts()
        {
            this.Components = new HashSet<Components>();
        }
    
        public int idCompontentReceipt { get; set; }
        public Nullable<int> idWoodDetail { get; set; }
        public Nullable<int> idTool { get; set; }
        public Nullable<int> idMachine { get; set; }
        public Nullable<int> idMetalDetail { get; set; }
    
        public virtual MetalDetails MetalDetails { get; set; }
        public virtual WoodDetails WoodDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Components> Components { get; set; }
    }
}
