//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpentryShop.CarpentryShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageProduct
    {
        public int idStorageProduct { get; set; }
        public int idProduct { get; set; }
        public int idStorage { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
